site_name: Non-Contact Laser Ultrasonic Testing Based on Neural Network Denoising
site_url: https://2p1c.github.io/Laser-NDT-Based-NN/
theme:
  name: material
  features:
    - footer.hide.copyright
  extra_css:
    - stylesheets/extra.css
